// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerStats.DAL;

#nullable disable

namespace PlayerStats.DAL.Migrations
{
    [DbContext(typeof(PlayerStatsContext))]
    [Migration("20231030174821_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("PlayerStats.Data.Models.Friend", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Friendname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f59862af-d4bb-454b-966c-baefbbaf0cb6"),
                            Friendname = "Melinda37",
                            PlayerID = new Guid("10836ada-4dcc-443a-b0c9-5d3d8aa9d57a")
                        },
                        new
                        {
                            ID = new Guid("c6d54db6-1696-4e6b-8509-df4669748481"),
                            Friendname = "Harriet.Abshire",
                            PlayerID = new Guid("ff9db84c-3a78-47ee-be4c-f080c98bb52b")
                        },
                        new
                        {
                            ID = new Guid("111fb07d-00dd-4e34-85dc-51c7a37b5d00"),
                            Friendname = "Cheryl_Rutherford",
                            PlayerID = new Guid("a71fe834-ec65-411f-a351-fdf7162bc151")
                        },
                        new
                        {
                            ID = new Guid("9677784a-2ad4-4dc9-9edd-88296430dbfb"),
                            Friendname = "Verna31",
                            PlayerID = new Guid("51add663-9d4d-4331-b9d2-cdcb87632548")
                        },
                        new
                        {
                            ID = new Guid("836b3c5a-f5be-4639-9c38-fc0807a8b09b"),
                            Friendname = "Walter98",
                            PlayerID = new Guid("eeb867ef-e5e0-4d83-b1d0-31148e84d772")
                        },
                        new
                        {
                            ID = new Guid("b5a9b1d6-9ed2-4265-b486-378dcf89c57e"),
                            Friendname = "Alton.Connelly",
                            PlayerID = new Guid("0783bd61-1e52-46f2-88f0-4e9bf6f6a88b")
                        },
                        new
                        {
                            ID = new Guid("45399727-118f-4f9e-9c4d-3e86532c5d1d"),
                            Friendname = "Anna_Lynch65",
                            PlayerID = new Guid("41aa18d8-5bcf-4d7f-9ea1-6126033e17fc")
                        },
                        new
                        {
                            ID = new Guid("a23a5a2a-b364-4682-9137-6fb577aa9bf4"),
                            Friendname = "Javier.Miller",
                            PlayerID = new Guid("cee0e022-f8e6-4a60-aedb-e425d2314f5a")
                        },
                        new
                        {
                            ID = new Guid("5d097fed-ef51-4b67-9e2a-79fdf162ba0e"),
                            Friendname = "Arnold.Murazik84",
                            PlayerID = new Guid("a71fe834-ec65-411f-a351-fdf7162bc151")
                        },
                        new
                        {
                            ID = new Guid("ad506d49-43fe-41f1-819f-74a93030c9f5"),
                            Friendname = "Anthony.Muller50",
                            PlayerID = new Guid("eeb867ef-e5e0-4d83-b1d0-31148e84d772")
                        },
                        new
                        {
                            ID = new Guid("a2698844-61ca-4a09-9ad8-660a45077622"),
                            Friendname = "Gretchen.Boyer",
                            PlayerID = new Guid("d0395477-058b-46df-86fd-a5593dde3b40")
                        },
                        new
                        {
                            ID = new Guid("405a368a-6ee5-47c5-9108-9d3302fa26ed"),
                            Friendname = "Mae.Satterfield64",
                            PlayerID = new Guid("615fa766-4a11-4e64-8a85-8c1271656937")
                        },
                        new
                        {
                            ID = new Guid("6b23400e-330d-4578-872f-4c1133e0777c"),
                            Friendname = "Lawrence_Gislason55",
                            PlayerID = new Guid("47240f49-8838-4b37-879b-4c7fd060c5bc")
                        },
                        new
                        {
                            ID = new Guid("bf873518-b81c-4b88-aa49-70c9a4920619"),
                            Friendname = "Mable.Waelchi3",
                            PlayerID = new Guid("cb12e787-7b31-417b-990d-8de66b99aac4")
                        },
                        new
                        {
                            ID = new Guid("4442f03e-55d5-4014-bb7d-80501ea25b16"),
                            Friendname = "Joe.Zulauf25",
                            PlayerID = new Guid("b304e995-91a3-4ac5-b44e-b98f99d42425")
                        },
                        new
                        {
                            ID = new Guid("21fbb439-8201-4d1b-bee4-c8b4d4fcf95c"),
                            Friendname = "Eleanor76",
                            PlayerID = new Guid("354a7e14-f789-4fde-ba1b-ced25965e92d")
                        },
                        new
                        {
                            ID = new Guid("e837719a-8bde-4a2c-a951-fc9a6fe9695f"),
                            Friendname = "Violet_Lang20",
                            PlayerID = new Guid("06fe26a4-47d4-4628-a5dc-c18d1f15b0d9")
                        },
                        new
                        {
                            ID = new Guid("0349ea85-77e6-4696-94ea-b6431d50a6cc"),
                            Friendname = "Judith_Fisher91",
                            PlayerID = new Guid("10836ada-4dcc-443a-b0c9-5d3d8aa9d57a")
                        },
                        new
                        {
                            ID = new Guid("ba28e56c-9f4d-46d7-8a90-c11d14f9025f"),
                            Friendname = "Andrew9",
                            PlayerID = new Guid("308567d4-5ff1-4ee5-a762-d06d3b36e3d7")
                        },
                        new
                        {
                            ID = new Guid("01d632f4-2635-4051-92ce-dca114d0caf2"),
                            Friendname = "Marco_Johnson",
                            PlayerID = new Guid("d0395477-058b-46df-86fd-a5593dde3b40")
                        },
                        new
                        {
                            ID = new Guid("9539ad3f-b82b-4fac-817a-7c0b5ac225dc"),
                            Friendname = "Nelson18",
                            PlayerID = new Guid("09ee2357-74bc-4cd9-8bbd-4863198d9da7")
                        },
                        new
                        {
                            ID = new Guid("036ce6f6-06a3-4a81-aad7-50429abfe73a"),
                            Friendname = "Bertha.Bruen21",
                            PlayerID = new Guid("41aa18d8-5bcf-4d7f-9ea1-6126033e17fc")
                        },
                        new
                        {
                            ID = new Guid("5d8917a9-5398-44a9-b2af-70af33abfd71"),
                            Friendname = "Ronnie38",
                            PlayerID = new Guid("308567d4-5ff1-4ee5-a762-d06d3b36e3d7")
                        },
                        new
                        {
                            ID = new Guid("e393885e-3e8e-4342-8b46-1c3e945ea1b3"),
                            Friendname = "Shelly_Kub52",
                            PlayerID = new Guid("cb12e787-7b31-417b-990d-8de66b99aac4")
                        },
                        new
                        {
                            ID = new Guid("03555ee3-4863-45f5-b462-df84a3b540fc"),
                            Friendname = "Lela_Yost54",
                            PlayerID = new Guid("10836ada-4dcc-443a-b0c9-5d3d8aa9d57a")
                        },
                        new
                        {
                            ID = new Guid("00981f8a-7318-4439-9883-96c7f439b4e9"),
                            Friendname = "Carmen.Koch9",
                            PlayerID = new Guid("b304e995-91a3-4ac5-b44e-b98f99d42425")
                        },
                        new
                        {
                            ID = new Guid("f6501fdb-2eab-415b-8577-2d5c793ac567"),
                            Friendname = "Edmund_West",
                            PlayerID = new Guid("334962bb-5d84-4748-bbae-ea30b4420e12")
                        },
                        new
                        {
                            ID = new Guid("62285a30-e542-4b84-9a93-29eb919a2474"),
                            Friendname = "Brett21",
                            PlayerID = new Guid("10836ada-4dcc-443a-b0c9-5d3d8aa9d57a")
                        },
                        new
                        {
                            ID = new Guid("15fc989f-0312-4f1d-bc83-e32091fe78c7"),
                            Friendname = "Cynthia.Brown15",
                            PlayerID = new Guid("0783bd61-1e52-46f2-88f0-4e9bf6f6a88b")
                        },
                        new
                        {
                            ID = new Guid("0c857436-c356-4b92-93d8-0d2508a80607"),
                            Friendname = "Evelyn_Williamson",
                            PlayerID = new Guid("ff9db84c-3a78-47ee-be4c-f080c98bb52b")
                        });
                });

            modelBuilder.Entity("PlayerStats.Data.Models.Player", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            ID = new Guid("51add663-9d4d-4331-b9d2-cdcb87632548"),
                            Rating = 680,
                            TotalGamesPlayed = 961,
                            Username = "Martha_Cremin",
                            Wins = 346
                        },
                        new
                        {
                            ID = new Guid("cb12e787-7b31-417b-990d-8de66b99aac4"),
                            Rating = 3545,
                            TotalGamesPlayed = 668,
                            Username = "Calvin71",
                            Wins = 191
                        },
                        new
                        {
                            ID = new Guid("09ee2357-74bc-4cd9-8bbd-4863198d9da7"),
                            Rating = 392,
                            TotalGamesPlayed = 746,
                            Username = "Judy.Lemke",
                            Wins = 452
                        },
                        new
                        {
                            ID = new Guid("615fa766-4a11-4e64-8a85-8c1271656937"),
                            Rating = 565,
                            TotalGamesPlayed = 917,
                            Username = "Dianne.Bernier97",
                            Wins = 318
                        },
                        new
                        {
                            ID = new Guid("d0c73a24-6ed3-42ff-956e-a2d3ddfddc74"),
                            Rating = 2752,
                            TotalGamesPlayed = 936,
                            Username = "Alan5",
                            Wins = 167
                        },
                        new
                        {
                            ID = new Guid("334962bb-5d84-4748-bbae-ea30b4420e12"),
                            Rating = 1153,
                            TotalGamesPlayed = 596,
                            Username = "Gerald_Swift",
                            Wins = 480
                        },
                        new
                        {
                            ID = new Guid("06fe26a4-47d4-4628-a5dc-c18d1f15b0d9"),
                            Rating = 3365,
                            TotalGamesPlayed = 665,
                            Username = "Jim_Ritchie24",
                            Wins = 405
                        },
                        new
                        {
                            ID = new Guid("2e488102-7e53-435d-978f-d10a1fa870aa"),
                            Rating = 3063,
                            TotalGamesPlayed = 142,
                            Username = "Jan.Weimann80",
                            Wins = 463
                        },
                        new
                        {
                            ID = new Guid("0783bd61-1e52-46f2-88f0-4e9bf6f6a88b"),
                            Rating = 4942,
                            TotalGamesPlayed = 672,
                            Username = "Orlando.Hand",
                            Wins = 260
                        },
                        new
                        {
                            ID = new Guid("7a9bca42-b153-4b7b-bd6b-d8d41d38c9ab"),
                            Rating = 130,
                            TotalGamesPlayed = 851,
                            Username = "Jody.Hessel",
                            Wins = 263
                        },
                        new
                        {
                            ID = new Guid("d0395477-058b-46df-86fd-a5593dde3b40"),
                            Rating = 1920,
                            TotalGamesPlayed = 630,
                            Username = "Heidi42",
                            Wins = 130
                        },
                        new
                        {
                            ID = new Guid("eeb867ef-e5e0-4d83-b1d0-31148e84d772"),
                            Rating = 4022,
                            TotalGamesPlayed = 99,
                            Username = "Donald_Reinger57",
                            Wins = 198
                        },
                        new
                        {
                            ID = new Guid("0f03d9f6-7e0f-4135-8c21-9a7e4451f965"),
                            Rating = 652,
                            TotalGamesPlayed = 196,
                            Username = "Marcella.Roob",
                            Wins = 37
                        },
                        new
                        {
                            ID = new Guid("a71fe834-ec65-411f-a351-fdf7162bc151"),
                            Rating = 1661,
                            TotalGamesPlayed = 321,
                            Username = "Darrin.Roob",
                            Wins = 454
                        },
                        new
                        {
                            ID = new Guid("830d7f42-fd93-43ec-a591-1de3573b39f7"),
                            Rating = 496,
                            TotalGamesPlayed = 24,
                            Username = "Maryann_Nienow",
                            Wins = 361
                        },
                        new
                        {
                            ID = new Guid("2371eb0e-2dc0-4190-aca2-b5b51b7a1585"),
                            Rating = 4631,
                            TotalGamesPlayed = 333,
                            Username = "Geraldine_Zboncak",
                            Wins = 79
                        },
                        new
                        {
                            ID = new Guid("af028519-704f-4b49-b255-95c51b1bb27d"),
                            Rating = 1771,
                            TotalGamesPlayed = 494,
                            Username = "Sylvester.Flatley",
                            Wins = 18
                        },
                        new
                        {
                            ID = new Guid("354a7e14-f789-4fde-ba1b-ced25965e92d"),
                            Rating = 372,
                            TotalGamesPlayed = 397,
                            Username = "Yvonne_Grant94",
                            Wins = 392
                        },
                        new
                        {
                            ID = new Guid("d1fbdaf0-e67f-4402-ae5b-c9177e2209de"),
                            Rating = 240,
                            TotalGamesPlayed = 95,
                            Username = "Christie_Schoen",
                            Wins = 75
                        },
                        new
                        {
                            ID = new Guid("308567d4-5ff1-4ee5-a762-d06d3b36e3d7"),
                            Rating = 1582,
                            TotalGamesPlayed = 659,
                            Username = "Mindy.Shanahan23",
                            Wins = 217
                        },
                        new
                        {
                            ID = new Guid("cb4b065e-7cf6-476e-bb77-7dda17d266c7"),
                            Rating = 2244,
                            TotalGamesPlayed = 705,
                            Username = "Roderick_Beahan63",
                            Wins = 86
                        },
                        new
                        {
                            ID = new Guid("cee0e022-f8e6-4a60-aedb-e425d2314f5a"),
                            Rating = 4643,
                            TotalGamesPlayed = 50,
                            Username = "Antonio_Dicki98",
                            Wins = 66
                        },
                        new
                        {
                            ID = new Guid("b304e995-91a3-4ac5-b44e-b98f99d42425"),
                            Rating = 3284,
                            TotalGamesPlayed = 400,
                            Username = "Jim32",
                            Wins = 123
                        },
                        new
                        {
                            ID = new Guid("eaf5cac5-b9c1-4a00-ba33-eaa4d22d88a7"),
                            Rating = 2267,
                            TotalGamesPlayed = 609,
                            Username = "Steve86",
                            Wins = 452
                        },
                        new
                        {
                            ID = new Guid("41aa18d8-5bcf-4d7f-9ea1-6126033e17fc"),
                            Rating = 2761,
                            TotalGamesPlayed = 241,
                            Username = "Ernest_Runte",
                            Wins = 211
                        },
                        new
                        {
                            ID = new Guid("f71e61bc-b633-4b8d-a50b-8522d7c937b2"),
                            Rating = 1877,
                            TotalGamesPlayed = 835,
                            Username = "Wallace49",
                            Wins = 427
                        },
                        new
                        {
                            ID = new Guid("6e9eece7-030c-4df2-8837-0f34512ae00a"),
                            Rating = 1136,
                            TotalGamesPlayed = 725,
                            Username = "Angelo18",
                            Wins = 302
                        },
                        new
                        {
                            ID = new Guid("47240f49-8838-4b37-879b-4c7fd060c5bc"),
                            Rating = 2500,
                            TotalGamesPlayed = 635,
                            Username = "Joel82",
                            Wins = 171
                        },
                        new
                        {
                            ID = new Guid("10836ada-4dcc-443a-b0c9-5d3d8aa9d57a"),
                            Rating = 1320,
                            TotalGamesPlayed = 119,
                            Username = "Debbie28",
                            Wins = 129
                        },
                        new
                        {
                            ID = new Guid("ff9db84c-3a78-47ee-be4c-f080c98bb52b"),
                            Rating = 3572,
                            TotalGamesPlayed = 419,
                            Username = "Melinda_Huel",
                            Wins = 445
                        });
                });

            modelBuilder.Entity("PlayerStats.Data.Models.Violation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Violations");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c90f8cee-0e88-4ff4-a57f-3b10bfb8049e"),
                            Description = "odio",
                            PlayerID = new Guid("51add663-9d4d-4331-b9d2-cdcb87632548"),
                            Type = "tenetur"
                        },
                        new
                        {
                            ID = new Guid("39c30532-08be-4e56-b3e1-a3b1217461c5"),
                            Description = "omnis",
                            PlayerID = new Guid("41aa18d8-5bcf-4d7f-9ea1-6126033e17fc"),
                            Type = "fugit"
                        },
                        new
                        {
                            ID = new Guid("385d4f85-f781-47e7-90a4-300644499bc2"),
                            Description = "sit",
                            PlayerID = new Guid("7a9bca42-b153-4b7b-bd6b-d8d41d38c9ab"),
                            Type = "repellat"
                        },
                        new
                        {
                            ID = new Guid("7061eb90-a28d-4898-8c11-58c344e2922d"),
                            Description = "aut",
                            PlayerID = new Guid("47240f49-8838-4b37-879b-4c7fd060c5bc"),
                            Type = "quas"
                        },
                        new
                        {
                            ID = new Guid("571e03eb-f845-47c2-af7c-089db1afa0d3"),
                            Description = "et",
                            PlayerID = new Guid("d1fbdaf0-e67f-4402-ae5b-c9177e2209de"),
                            Type = "eum"
                        },
                        new
                        {
                            ID = new Guid("6756bdfb-76f0-4dc3-be0c-5f9ca9fc1a44"),
                            Description = "qui",
                            PlayerID = new Guid("51add663-9d4d-4331-b9d2-cdcb87632548"),
                            Type = "occaecati"
                        },
                        new
                        {
                            ID = new Guid("109cb07a-20d1-4c46-8804-c9c56b13a7b5"),
                            Description = "necessitatibus",
                            PlayerID = new Guid("ff9db84c-3a78-47ee-be4c-f080c98bb52b"),
                            Type = "et"
                        },
                        new
                        {
                            ID = new Guid("2035d3a3-4603-440f-842a-6037940a8342"),
                            Description = "voluptatem",
                            PlayerID = new Guid("354a7e14-f789-4fde-ba1b-ced25965e92d"),
                            Type = "occaecati"
                        },
                        new
                        {
                            ID = new Guid("d1c05f7d-a303-45b5-9430-b5da68d12545"),
                            Description = "sit",
                            PlayerID = new Guid("cb12e787-7b31-417b-990d-8de66b99aac4"),
                            Type = "amet"
                        },
                        new
                        {
                            ID = new Guid("88f38fa3-1ca8-4273-a6bb-17b7884bb16d"),
                            Description = "consectetur",
                            PlayerID = new Guid("51add663-9d4d-4331-b9d2-cdcb87632548"),
                            Type = "mollitia"
                        },
                        new
                        {
                            ID = new Guid("7a154e09-178b-4fda-9e02-a944486259a7"),
                            Description = "animi",
                            PlayerID = new Guid("830d7f42-fd93-43ec-a591-1de3573b39f7"),
                            Type = "nam"
                        },
                        new
                        {
                            ID = new Guid("dbb22c65-275a-469f-95a2-595210a0de51"),
                            Description = "dolores",
                            PlayerID = new Guid("7a9bca42-b153-4b7b-bd6b-d8d41d38c9ab"),
                            Type = "sequi"
                        },
                        new
                        {
                            ID = new Guid("2de01f99-8e0a-4c6a-974a-6d3ddd4caa14"),
                            Description = "accusamus",
                            PlayerID = new Guid("06fe26a4-47d4-4628-a5dc-c18d1f15b0d9"),
                            Type = "non"
                        },
                        new
                        {
                            ID = new Guid("32ac7b23-f562-41fb-a6fa-232c8f25ee6e"),
                            Description = "et",
                            PlayerID = new Guid("d0395477-058b-46df-86fd-a5593dde3b40"),
                            Type = "sapiente"
                        },
                        new
                        {
                            ID = new Guid("69a3a9dc-078b-429a-964b-ac70b51d9bdb"),
                            Description = "sed",
                            PlayerID = new Guid("47240f49-8838-4b37-879b-4c7fd060c5bc"),
                            Type = "est"
                        },
                        new
                        {
                            ID = new Guid("da05257d-8d53-44f3-b477-8737df867410"),
                            Description = "sunt",
                            PlayerID = new Guid("830d7f42-fd93-43ec-a591-1de3573b39f7"),
                            Type = "et"
                        },
                        new
                        {
                            ID = new Guid("0a596d51-eebb-4e6b-b6b8-2b7a3aa30edf"),
                            Description = "est",
                            PlayerID = new Guid("a71fe834-ec65-411f-a351-fdf7162bc151"),
                            Type = "blanditiis"
                        },
                        new
                        {
                            ID = new Guid("79cb595f-06a7-4d32-b428-0466aa47fc12"),
                            Description = "inventore",
                            PlayerID = new Guid("cb12e787-7b31-417b-990d-8de66b99aac4"),
                            Type = "ea"
                        },
                        new
                        {
                            ID = new Guid("6fc925a0-fb40-4b3e-9a6c-27a154476b2a"),
                            Description = "reprehenderit",
                            PlayerID = new Guid("cb4b065e-7cf6-476e-bb77-7dda17d266c7"),
                            Type = "iure"
                        },
                        new
                        {
                            ID = new Guid("9c807a80-610a-47c9-822c-8daaa70d2c4f"),
                            Description = "sit",
                            PlayerID = new Guid("0783bd61-1e52-46f2-88f0-4e9bf6f6a88b"),
                            Type = "natus"
                        },
                        new
                        {
                            ID = new Guid("06357afd-20c7-4b4e-b254-bf9b682fa5d3"),
                            Description = "vitae",
                            PlayerID = new Guid("41aa18d8-5bcf-4d7f-9ea1-6126033e17fc"),
                            Type = "aut"
                        },
                        new
                        {
                            ID = new Guid("e4f34095-1cf5-4dfb-9ad9-453d63172428"),
                            Description = "quos",
                            PlayerID = new Guid("615fa766-4a11-4e64-8a85-8c1271656937"),
                            Type = "odit"
                        },
                        new
                        {
                            ID = new Guid("7bcb2427-0eac-4322-a709-3eabd9e518f3"),
                            Description = "ullam",
                            PlayerID = new Guid("cee0e022-f8e6-4a60-aedb-e425d2314f5a"),
                            Type = "qui"
                        },
                        new
                        {
                            ID = new Guid("939c297b-4ee7-4589-acbe-190124324f34"),
                            Description = "ipsum",
                            PlayerID = new Guid("eeb867ef-e5e0-4d83-b1d0-31148e84d772"),
                            Type = "voluptas"
                        },
                        new
                        {
                            ID = new Guid("3f083cc7-0918-4e7f-94ca-cb1a02021301"),
                            Description = "laboriosam",
                            PlayerID = new Guid("eeb867ef-e5e0-4d83-b1d0-31148e84d772"),
                            Type = "accusamus"
                        },
                        new
                        {
                            ID = new Guid("979af70e-0b6a-495b-852c-15d8c0decb59"),
                            Description = "enim",
                            PlayerID = new Guid("eaf5cac5-b9c1-4a00-ba33-eaa4d22d88a7"),
                            Type = "impedit"
                        },
                        new
                        {
                            ID = new Guid("38c30985-08ee-48eb-8166-c6061ea019b1"),
                            Description = "mollitia",
                            PlayerID = new Guid("354a7e14-f789-4fde-ba1b-ced25965e92d"),
                            Type = "quas"
                        },
                        new
                        {
                            ID = new Guid("b40a0260-fb20-4476-873d-e057ec01a199"),
                            Description = "optio",
                            PlayerID = new Guid("ff9db84c-3a78-47ee-be4c-f080c98bb52b"),
                            Type = "ipsum"
                        },
                        new
                        {
                            ID = new Guid("3bd23e0e-df19-4024-bcac-b2399c6c6b75"),
                            Description = "maxime",
                            PlayerID = new Guid("47240f49-8838-4b37-879b-4c7fd060c5bc"),
                            Type = "sed"
                        },
                        new
                        {
                            ID = new Guid("11fb2f5f-483f-448a-8bc9-7947086304a6"),
                            Description = "minima",
                            PlayerID = new Guid("41aa18d8-5bcf-4d7f-9ea1-6126033e17fc"),
                            Type = "ut"
                        });
                });

            modelBuilder.Entity("PlayerStats.Data.Models.Friend", b =>
                {
                    b.HasOne("PlayerStats.Data.Models.Player", "Player")
                        .WithMany("Friends")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlayerStats.Data.Models.Violation", b =>
                {
                    b.HasOne("PlayerStats.Data.Models.Player", "Player")
                        .WithMany("Violations")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlayerStats.Data.Models.Player", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
