// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skins.DAL;

#nullable disable

namespace Skins.DAL.Migrations
{
    [DbContext(typeof(SkinsContext))]
    partial class SkinsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Skins.Data.Models.Character", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceOfCharacter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            ID = new Guid("d5db1a45-19d2-4b4c-8e1d-14e4b95ce70d"),
                            Name = "Hilda",
                            RaceOfCharacter = "nisi",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("1bda794e-1552-40e0-afb0-f64d924136cc"),
                            Name = "Jessica",
                            RaceOfCharacter = "eius",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("84b5779e-012f-4a34-b992-c389e2d8864b"),
                            Name = "Juana",
                            RaceOfCharacter = "id",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("7f0e7ba5-7635-451f-8de9-98f4937e0424"),
                            Name = "Nora",
                            RaceOfCharacter = "ab",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("6ffbe56d-897f-428b-a493-8c5335f08d17"),
                            Name = "Kelly",
                            RaceOfCharacter = "corrupti",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("242acdbe-b839-46b7-8d37-fecdcac83ee3"),
                            Name = "Freddie",
                            RaceOfCharacter = "enim",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("14b54d9d-5f39-4db2-a7af-c116b0549def"),
                            Name = "Elijah",
                            RaceOfCharacter = "quod",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("c5ee9577-66c4-4862-ae59-b0af6c988a24"),
                            Name = "Brittany",
                            RaceOfCharacter = "vel",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("3f143503-4f80-438b-8d02-4b9634b5e50d"),
                            Name = "Roosevelt",
                            RaceOfCharacter = "ut",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("07868e4b-4ca3-4ccd-a514-7a40c183b239"),
                            Name = "Ella",
                            RaceOfCharacter = "et",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("7d5ccb14-9e76-4fb6-a242-f46c8b7cc871"),
                            Name = "Trevor",
                            RaceOfCharacter = "necessitatibus",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("69db49c3-cbf7-4860-9cfb-1ad56b56fbdc"),
                            Name = "Terry",
                            RaceOfCharacter = "sint",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("c1cea1ce-90fd-446a-b89a-0d240c697d0a"),
                            Name = "Juan",
                            RaceOfCharacter = "harum",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("675c5103-4f0a-4fc9-8fbc-2cf2b3680cf8"),
                            Name = "Lorene",
                            RaceOfCharacter = "voluptatem",
                            Rarity = 4
                        },
                        new
                        {
                            ID = new Guid("43aea403-10ea-46bf-8a9a-fb90434f6460"),
                            Name = "Willis",
                            RaceOfCharacter = "veritatis",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("c31f5463-3c4e-4e17-a6b2-6c2dc3314e0c"),
                            Name = "Alicia",
                            RaceOfCharacter = "quam",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("e9b4541a-1f25-4a3e-b678-d56c1bf808c5"),
                            Name = "Jean",
                            RaceOfCharacter = "et",
                            Rarity = 5
                        },
                        new
                        {
                            ID = new Guid("6983e121-8efb-47cf-b63d-39364cd9cbdc"),
                            Name = "Krista",
                            RaceOfCharacter = "exercitationem",
                            Rarity = 4
                        },
                        new
                        {
                            ID = new Guid("828779aa-727f-495d-995d-287f6e47af25"),
                            Name = "Terence",
                            RaceOfCharacter = "ratione",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("5b281a24-6503-4650-aa56-bc4e235e2cb0"),
                            Name = "Jesse",
                            RaceOfCharacter = "et",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("f93d8370-8e7c-42e0-9d2f-33e01412f05d"),
                            Name = "Brenda",
                            RaceOfCharacter = "quia",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("5a423f94-6c6d-43ef-8ed6-0733002948f2"),
                            Name = "Joseph",
                            RaceOfCharacter = "et",
                            Rarity = 5
                        },
                        new
                        {
                            ID = new Guid("5255c4e3-6244-4ae3-ad37-ec43043905bf"),
                            Name = "Garry",
                            RaceOfCharacter = "voluptates",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("887100da-337f-4f17-b18a-a2065646c7b8"),
                            Name = "Josephine",
                            RaceOfCharacter = "nisi",
                            Rarity = 5
                        },
                        new
                        {
                            ID = new Guid("97814a50-1efa-4beb-8793-68f5c7969237"),
                            Name = "Antoinette",
                            RaceOfCharacter = "eum",
                            Rarity = 4
                        },
                        new
                        {
                            ID = new Guid("f6fcc26b-4a0f-4cc1-bf02-63336aed6b55"),
                            Name = "Martin",
                            RaceOfCharacter = "asperiores",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("0ee808aa-ea32-4b51-9fb3-19886c91ca03"),
                            Name = "Chad",
                            RaceOfCharacter = "quas",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("bc853465-9558-4766-82d0-9831451d4dc4"),
                            Name = "Luz",
                            RaceOfCharacter = "atque",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("4547c345-8e5b-4c92-bce5-908e8d4cb984"),
                            Name = "Myra",
                            RaceOfCharacter = "exercitationem",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("9025bec3-2c90-40fd-9ce6-960347ad6a0f"),
                            Name = "Seth",
                            RaceOfCharacter = "mollitia",
                            Rarity = 1
                        });
                });

            modelBuilder.Entity("Skins.Data.Models.Pet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CharacterID")
                        .HasColumnType("TEXT");

                    b.Property<string>("KindOfAnimal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID")
                        .IsUnique();

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            ID = new Guid("8659367e-3d51-40f5-bb45-78b6fb287b15"),
                            CharacterID = new Guid("d5db1a45-19d2-4b4c-8e1d-14e4b95ce70d"),
                            KindOfAnimal = "voluptatibus",
                            Name = "Shirley",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("1d0707cc-e340-419e-929d-b38d84bede04"),
                            CharacterID = new Guid("1bda794e-1552-40e0-afb0-f64d924136cc"),
                            KindOfAnimal = "ut",
                            Name = "Christine",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("63692750-dda7-4271-afe0-dd60aea80189"),
                            CharacterID = new Guid("84b5779e-012f-4a34-b992-c389e2d8864b"),
                            KindOfAnimal = "dicta",
                            Name = "Carrie",
                            Rarity = 4
                        },
                        new
                        {
                            ID = new Guid("85da6d9b-9b8a-452d-86d3-f30e0b723f4d"),
                            CharacterID = new Guid("7f0e7ba5-7635-451f-8de9-98f4937e0424"),
                            KindOfAnimal = "odit",
                            Name = "Hugo",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("12fb7be2-3e43-43c7-b17f-616177d6a4a3"),
                            CharacterID = new Guid("6ffbe56d-897f-428b-a493-8c5335f08d17"),
                            KindOfAnimal = "tenetur",
                            Name = "Darryl",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("a3740a30-b4d6-4817-a420-09222ddb70c5"),
                            CharacterID = new Guid("242acdbe-b839-46b7-8d37-fecdcac83ee3"),
                            KindOfAnimal = "excepturi",
                            Name = "Heidi",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("1784922e-6b56-49d6-aff8-0caac71c5c01"),
                            CharacterID = new Guid("14b54d9d-5f39-4db2-a7af-c116b0549def"),
                            KindOfAnimal = "illum",
                            Name = "Bonnie",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("e9edc8c9-efbd-4f14-8f59-361a97e46a69"),
                            CharacterID = new Guid("c5ee9577-66c4-4862-ae59-b0af6c988a24"),
                            KindOfAnimal = "et",
                            Name = "Carol",
                            Rarity = 5
                        },
                        new
                        {
                            ID = new Guid("b1e9237a-e06f-4399-b771-c22778f5f86f"),
                            CharacterID = new Guid("3f143503-4f80-438b-8d02-4b9634b5e50d"),
                            KindOfAnimal = "eius",
                            Name = "Sonja",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("5041d4b8-0674-4879-9ade-a568430c68ba"),
                            CharacterID = new Guid("07868e4b-4ca3-4ccd-a514-7a40c183b239"),
                            KindOfAnimal = "ea",
                            Name = "Vivian",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("9722e064-d2ff-4264-82ec-501bd65a6ec0"),
                            CharacterID = new Guid("7d5ccb14-9e76-4fb6-a242-f46c8b7cc871"),
                            KindOfAnimal = "molestias",
                            Name = "John",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("ada9e2f8-e854-4200-94ab-fe176736e99b"),
                            CharacterID = new Guid("69db49c3-cbf7-4860-9cfb-1ad56b56fbdc"),
                            KindOfAnimal = "voluptate",
                            Name = "Damon",
                            Rarity = 3
                        },
                        new
                        {
                            ID = new Guid("ea1383b7-61bf-46e6-a7a2-a2a24b7c6559"),
                            CharacterID = new Guid("c1cea1ce-90fd-446a-b89a-0d240c697d0a"),
                            KindOfAnimal = "unde",
                            Name = "Yvette",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("5d0f4bde-2af7-4705-94cf-abf9198325e5"),
                            CharacterID = new Guid("675c5103-4f0a-4fc9-8fbc-2cf2b3680cf8"),
                            KindOfAnimal = "voluptatem",
                            Name = "Marcia",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("3dd749a9-d228-4783-a711-fa4c43fee43b"),
                            CharacterID = new Guid("43aea403-10ea-46bf-8a9a-fb90434f6460"),
                            KindOfAnimal = "non",
                            Name = "Alfonso",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("488a0a76-4468-44ce-987d-e4c7570e227d"),
                            CharacterID = new Guid("c31f5463-3c4e-4e17-a6b2-6c2dc3314e0c"),
                            KindOfAnimal = "neque",
                            Name = "Jon",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("5b59bc16-7586-4985-9b2d-2667691bb127"),
                            CharacterID = new Guid("e9b4541a-1f25-4a3e-b678-d56c1bf808c5"),
                            KindOfAnimal = "omnis",
                            Name = "Rhonda",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("a47be091-9b8f-4d57-939b-a3003ae55cae"),
                            CharacterID = new Guid("6983e121-8efb-47cf-b63d-39364cd9cbdc"),
                            KindOfAnimal = "consequatur",
                            Name = "Wallace",
                            Rarity = 5
                        },
                        new
                        {
                            ID = new Guid("3ba70ea6-d4e2-4a99-94ec-0d058aaebac4"),
                            CharacterID = new Guid("828779aa-727f-495d-995d-287f6e47af25"),
                            KindOfAnimal = "qui",
                            Name = "Cody",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("842768a3-a661-480a-8444-bd292dacee9f"),
                            CharacterID = new Guid("5b281a24-6503-4650-aa56-bc4e235e2cb0"),
                            KindOfAnimal = "autem",
                            Name = "Mario",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("92d8261a-6e4b-47bf-90ab-0f14dc3cb542"),
                            CharacterID = new Guid("f93d8370-8e7c-42e0-9d2f-33e01412f05d"),
                            KindOfAnimal = "nisi",
                            Name = "Joy",
                            Rarity = 5
                        },
                        new
                        {
                            ID = new Guid("f7e8d1b8-b35c-4ca4-abef-628dd80bbfca"),
                            CharacterID = new Guid("5a423f94-6c6d-43ef-8ed6-0733002948f2"),
                            KindOfAnimal = "eius",
                            Name = "Clinton",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("60b797ae-8024-44a7-92ed-87bf0894c330"),
                            CharacterID = new Guid("5255c4e3-6244-4ae3-ad37-ec43043905bf"),
                            KindOfAnimal = "voluptatem",
                            Name = "Marcella",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("e7321fab-be9d-4488-9d21-373f669f8022"),
                            CharacterID = new Guid("887100da-337f-4f17-b18a-a2065646c7b8"),
                            KindOfAnimal = "voluptas",
                            Name = "Brett",
                            Rarity = 0
                        },
                        new
                        {
                            ID = new Guid("8d202163-b5d1-49b9-a52c-1d0b95d700e8"),
                            CharacterID = new Guid("97814a50-1efa-4beb-8793-68f5c7969237"),
                            KindOfAnimal = "officia",
                            Name = "Sylvia",
                            Rarity = 4
                        },
                        new
                        {
                            ID = new Guid("67de6ef9-6504-44cd-aec9-784d6716c360"),
                            CharacterID = new Guid("f6fcc26b-4a0f-4cc1-bf02-63336aed6b55"),
                            KindOfAnimal = "blanditiis",
                            Name = "Steven",
                            Rarity = 5
                        },
                        new
                        {
                            ID = new Guid("aef4ae0c-893b-4d9a-b372-1ed8b5ab9fd6"),
                            CharacterID = new Guid("0ee808aa-ea32-4b51-9fb3-19886c91ca03"),
                            KindOfAnimal = "qui",
                            Name = "Gilberto",
                            Rarity = 2
                        },
                        new
                        {
                            ID = new Guid("23673694-2010-48f9-b016-1013a5e0e5d0"),
                            CharacterID = new Guid("bc853465-9558-4766-82d0-9831451d4dc4"),
                            KindOfAnimal = "nesciunt",
                            Name = "Vicky",
                            Rarity = 4
                        },
                        new
                        {
                            ID = new Guid("ffbb8486-f249-4cc5-b374-493c6d80c7aa"),
                            CharacterID = new Guid("4547c345-8e5b-4c92-bce5-908e8d4cb984"),
                            KindOfAnimal = "rerum",
                            Name = "Beverly",
                            Rarity = 1
                        },
                        new
                        {
                            ID = new Guid("45387e68-40b2-4367-bbcb-a0bb17aa3206"),
                            CharacterID = new Guid("9025bec3-2c90-40fd-9ce6-960347ad6a0f"),
                            KindOfAnimal = "natus",
                            Name = "Hugh",
                            Rarity = 2
                        });
                });

            modelBuilder.Entity("Skins.Data.Models.Weapon", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CharacterID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeOfWeapon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID")
                        .IsUnique();

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ab640046-e41d-4217-be61-67f03cd25e9f"),
                            CharacterID = new Guid("d5db1a45-19d2-4b4c-8e1d-14e4b95ce70d"),
                            Name = "Elizabeth",
                            Rarity = 0,
                            TypeOfWeapon = "voluptatem"
                        },
                        new
                        {
                            ID = new Guid("29c7b7a8-9813-4976-b7d1-02387d10bce4"),
                            CharacterID = new Guid("1bda794e-1552-40e0-afb0-f64d924136cc"),
                            Name = "Cedric",
                            Rarity = 1,
                            TypeOfWeapon = "quia"
                        },
                        new
                        {
                            ID = new Guid("6c3214aa-a96e-4c9b-9c75-9c7e7e6a14be"),
                            CharacterID = new Guid("84b5779e-012f-4a34-b992-c389e2d8864b"),
                            Name = "Robin",
                            Rarity = 1,
                            TypeOfWeapon = "nihil"
                        },
                        new
                        {
                            ID = new Guid("4b02ff00-d83f-4ef1-9131-12f81c936f09"),
                            CharacterID = new Guid("7f0e7ba5-7635-451f-8de9-98f4937e0424"),
                            Name = "Toni",
                            Rarity = 4,
                            TypeOfWeapon = "accusantium"
                        },
                        new
                        {
                            ID = new Guid("98ddb1f8-cc43-431d-b5ea-fed15876ba6f"),
                            CharacterID = new Guid("6ffbe56d-897f-428b-a493-8c5335f08d17"),
                            Name = "Rene",
                            Rarity = 3,
                            TypeOfWeapon = "perferendis"
                        },
                        new
                        {
                            ID = new Guid("6ce732d6-54ec-434d-b7a2-6299a99ee57d"),
                            CharacterID = new Guid("242acdbe-b839-46b7-8d37-fecdcac83ee3"),
                            Name = "Devin",
                            Rarity = 5,
                            TypeOfWeapon = "quaerat"
                        },
                        new
                        {
                            ID = new Guid("81cb8949-1f4e-485b-992c-5b861cbe4e95"),
                            CharacterID = new Guid("14b54d9d-5f39-4db2-a7af-c116b0549def"),
                            Name = "Brent",
                            Rarity = 4,
                            TypeOfWeapon = "earum"
                        },
                        new
                        {
                            ID = new Guid("54be799c-971a-4781-8e5a-943d8be987f0"),
                            CharacterID = new Guid("c5ee9577-66c4-4862-ae59-b0af6c988a24"),
                            Name = "Sonia",
                            Rarity = 2,
                            TypeOfWeapon = "voluptatem"
                        },
                        new
                        {
                            ID = new Guid("a6e8e985-20bd-4281-9214-9cafdfd0f784"),
                            CharacterID = new Guid("3f143503-4f80-438b-8d02-4b9634b5e50d"),
                            Name = "Gregg",
                            Rarity = 1,
                            TypeOfWeapon = "quisquam"
                        },
                        new
                        {
                            ID = new Guid("08d2dd3f-5b69-4080-835e-833ce7fdbc8a"),
                            CharacterID = new Guid("07868e4b-4ca3-4ccd-a514-7a40c183b239"),
                            Name = "Wallace",
                            Rarity = 2,
                            TypeOfWeapon = "earum"
                        },
                        new
                        {
                            ID = new Guid("ef8b6615-76d5-4bcf-9276-c9f0bb17a4cd"),
                            CharacterID = new Guid("7d5ccb14-9e76-4fb6-a242-f46c8b7cc871"),
                            Name = "Tracy",
                            Rarity = 4,
                            TypeOfWeapon = "et"
                        },
                        new
                        {
                            ID = new Guid("38fc261d-5d4e-4334-bd65-044a34883820"),
                            CharacterID = new Guid("69db49c3-cbf7-4860-9cfb-1ad56b56fbdc"),
                            Name = "Patrick",
                            Rarity = 2,
                            TypeOfWeapon = "omnis"
                        },
                        new
                        {
                            ID = new Guid("c0c37481-32be-4373-84d9-4e4573f2b0cb"),
                            CharacterID = new Guid("c1cea1ce-90fd-446a-b89a-0d240c697d0a"),
                            Name = "Abel",
                            Rarity = 0,
                            TypeOfWeapon = "tenetur"
                        },
                        new
                        {
                            ID = new Guid("10a2dd77-d409-455e-bbfd-abfa1a1360c8"),
                            CharacterID = new Guid("675c5103-4f0a-4fc9-8fbc-2cf2b3680cf8"),
                            Name = "Gail",
                            Rarity = 5,
                            TypeOfWeapon = "minus"
                        },
                        new
                        {
                            ID = new Guid("add716dc-4527-4a41-aa48-1bb91bbe0592"),
                            CharacterID = new Guid("43aea403-10ea-46bf-8a9a-fb90434f6460"),
                            Name = "Alexandra",
                            Rarity = 4,
                            TypeOfWeapon = "voluptatem"
                        },
                        new
                        {
                            ID = new Guid("a736f6a1-021a-401f-9f39-081777720619"),
                            CharacterID = new Guid("c31f5463-3c4e-4e17-a6b2-6c2dc3314e0c"),
                            Name = "Christie",
                            Rarity = 5,
                            TypeOfWeapon = "ut"
                        },
                        new
                        {
                            ID = new Guid("fa597a8c-9e55-4d2c-b612-207eeb2fc71a"),
                            CharacterID = new Guid("e9b4541a-1f25-4a3e-b678-d56c1bf808c5"),
                            Name = "Bert",
                            Rarity = 5,
                            TypeOfWeapon = "nesciunt"
                        },
                        new
                        {
                            ID = new Guid("ae6eeff7-77d7-4d51-add6-d8183f902800"),
                            CharacterID = new Guid("6983e121-8efb-47cf-b63d-39364cd9cbdc"),
                            Name = "Cathy",
                            Rarity = 5,
                            TypeOfWeapon = "dolor"
                        },
                        new
                        {
                            ID = new Guid("ba296e46-1915-44e9-84bf-949d23eef9da"),
                            CharacterID = new Guid("828779aa-727f-495d-995d-287f6e47af25"),
                            Name = "Bernice",
                            Rarity = 4,
                            TypeOfWeapon = "nesciunt"
                        },
                        new
                        {
                            ID = new Guid("e46dc932-00ef-4950-a3b7-0793f8aebd59"),
                            CharacterID = new Guid("5b281a24-6503-4650-aa56-bc4e235e2cb0"),
                            Name = "Nichole",
                            Rarity = 5,
                            TypeOfWeapon = "voluptatum"
                        },
                        new
                        {
                            ID = new Guid("7b87762d-1122-4a53-9055-f5f39a6ec1fe"),
                            CharacterID = new Guid("f93d8370-8e7c-42e0-9d2f-33e01412f05d"),
                            Name = "Angel",
                            Rarity = 3,
                            TypeOfWeapon = "et"
                        },
                        new
                        {
                            ID = new Guid("f7e6ef38-360f-42ab-b10a-b93a21332f0b"),
                            CharacterID = new Guid("5a423f94-6c6d-43ef-8ed6-0733002948f2"),
                            Name = "Norman",
                            Rarity = 2,
                            TypeOfWeapon = "ab"
                        },
                        new
                        {
                            ID = new Guid("2947b70b-1f3b-4e73-9a11-16299df6fa31"),
                            CharacterID = new Guid("5255c4e3-6244-4ae3-ad37-ec43043905bf"),
                            Name = "Kim",
                            Rarity = 3,
                            TypeOfWeapon = "et"
                        },
                        new
                        {
                            ID = new Guid("57f68038-b464-43b0-82ac-9c0997253592"),
                            CharacterID = new Guid("887100da-337f-4f17-b18a-a2065646c7b8"),
                            Name = "Jeanne",
                            Rarity = 4,
                            TypeOfWeapon = "soluta"
                        },
                        new
                        {
                            ID = new Guid("2a54ae38-6729-4456-9efc-9cd83839033a"),
                            CharacterID = new Guid("97814a50-1efa-4beb-8793-68f5c7969237"),
                            Name = "Steven",
                            Rarity = 5,
                            TypeOfWeapon = "aliquid"
                        },
                        new
                        {
                            ID = new Guid("a748f7fb-18c3-4d2e-aecf-1af09cb5a963"),
                            CharacterID = new Guid("f6fcc26b-4a0f-4cc1-bf02-63336aed6b55"),
                            Name = "Douglas",
                            Rarity = 5,
                            TypeOfWeapon = "non"
                        },
                        new
                        {
                            ID = new Guid("4a964ded-735e-4ca5-9061-68bf8f003b1d"),
                            CharacterID = new Guid("0ee808aa-ea32-4b51-9fb3-19886c91ca03"),
                            Name = "Alicia",
                            Rarity = 2,
                            TypeOfWeapon = "est"
                        },
                        new
                        {
                            ID = new Guid("33f48c89-c7d4-4706-8ccb-7ad97c5fbd44"),
                            CharacterID = new Guid("bc853465-9558-4766-82d0-9831451d4dc4"),
                            Name = "Rick",
                            Rarity = 4,
                            TypeOfWeapon = "aut"
                        },
                        new
                        {
                            ID = new Guid("66baf759-b6cd-4217-9bae-cb5fb0d693b1"),
                            CharacterID = new Guid("4547c345-8e5b-4c92-bce5-908e8d4cb984"),
                            Name = "Meredith",
                            Rarity = 1,
                            TypeOfWeapon = "maiores"
                        },
                        new
                        {
                            ID = new Guid("bac7e120-42da-45e8-b8a4-8be879d425d4"),
                            CharacterID = new Guid("9025bec3-2c90-40fd-9ce6-960347ad6a0f"),
                            Name = "Irma",
                            Rarity = 1,
                            TypeOfWeapon = "dolores"
                        });
                });

            modelBuilder.Entity("Skins.Data.Models.Pet", b =>
                {
                    b.HasOne("Skins.Data.Models.Character", "Character")
                        .WithOne("Pet")
                        .HasForeignKey("Skins.Data.Models.Pet", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Skins.Data.Models.Weapon", b =>
                {
                    b.HasOne("Skins.Data.Models.Character", "Character")
                        .WithOne("Weapon")
                        .HasForeignKey("Skins.Data.Models.Weapon", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Skins.Data.Models.Character", b =>
                {
                    b.Navigation("Pet")
                        .IsRequired();

                    b.Navigation("Weapon")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
